services:
  coverbound:
    build: .
    container_name: coverbound-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file: "coverbound.env"
    restart: unless-stopped
